# Generated by Django 4.0.5 on 2022-07-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Side Dish', 'Side Dish'), ('Drink', 'Drink'), ('Dessert', 'Dessert'), ('Appetizer', 'Appetizer'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Main Dish', 'Main Dish')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
