# Generated by Django 4.0.5 on 2022-07-03 18:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('dish_type', models.CharField(choices=[('Drink', 'Drink'), ('Soup', 'Soup'), ('Dessert', 'Dessert'), ('Salad', 'Salad'), ('Appetizer', 'Appetizer'), ('Main Dish', 'Main Dish'), ('Side Dish', 'Side Dish')], max_length=100)),
                ('prep_time_mins', models.PositiveIntegerField()),
                ('no_of_servings', models.PositiveIntegerField()),
                ('cooking_time_mins', models.PositiveIntegerField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='recipe_images')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('bookmarked', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
