# Generated by Django 4.0.5 on 2022-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0004_alter_recipe_dish_type_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Main Dish', 'Main Dish'), ('Salad', 'Salad'), ('Drink', 'Drink'), ('Appetizer', 'Appetizer'), ('Soup', 'Soup'), ('Side Dish', 'Side Dish'), ('Dessert', 'Dessert')], max_length=100),
        ),
    ]
