# Generated by Django 4.0.6 on 2022-07-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0006_alter_profile_user_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Salad', 'Salad'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Main Dish', 'Main Dish'), ('Dessert', 'Dessert'), ('Appetizer', 'Appetizer'), ('Side Dish', 'Side Dish')], max_length=100),
        ),
    ]
