# Generated by Django 4.0.6 on 2022-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0011_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Main Dish', 'Main Dish'), ('Side Dish', 'Side Dish'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Salad', 'Salad'), ('Soup', 'Soup'), ('Appetizer', 'Appetizer')], max_length=100),
        ),
    ]
