# Generated by Django 4.0.6 on 2022-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0012_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratings',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Salad', 'Salad'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Appetizer', 'Appetizer'), ('Dessert', 'Dessert'), ('Side Dish', 'Side Dish'), ('Main Dish', 'Main Dish')], max_length=100),
        ),
    ]
