# Generated by Django 4.0.6 on 2022-07-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0014_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Side Dish', 'Side Dish'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Appetizer', 'Appetizer'), ('Salad', 'Salad'), ('Main Dish', 'Main Dish'), ('Soup', 'Soup')], max_length=100),
        ),
    ]
