# Generated by Django 4.0.6 on 2022-07-13 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_api', '0018_alter_recipe_dish_type_alter_recipe_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Soup', 'Soup'), ('Main Dish', 'Main Dish'), ('Drink', 'Drink'), ('Salad', 'Salad'), ('Dessert', 'Dessert'), ('Side Dish', 'Side Dish')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
