# Generated by Django 4.0.6 on 2022-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0019_alter_recipe_dish_type_alter_recipe_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Main Dish', 'Main Dish'), ('Salad', 'Salad'), ('Soup', 'Soup'), ('Appetizer', 'Appetizer'), ('Side Dish', 'Side Dish'), ('Drink', 'Drink')], max_length=100),
        ),
    ]
