# Generated by Django 4.0.6 on 2022-07-13 11:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0022_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Salad', 'Salad'), ('Soup', 'Soup'), ('Side Dish', 'Side Dish'), ('Drink', 'Drink'), ('Appetizer', 'Appetizer'), ('Main Dish', 'Main Dish')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='recipe_images'),
        ),
    ]
